# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField(blank=True, null=True)),
                ('cardinality_csvlevel', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('consumerid', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('perishable_token', models.TextField(blank=True, null=True)),
                ('cardinality_csv_session_token', models.TextField(blank=True, null=True)),
                ('cardinality_csvregid', models.TextField(blank=True, null=True)),
                ('cardinality_csvusername', models.TextField(blank=True, null=True)),
                ('cardinality_csv_updated_at', models.TextField(blank=True, null=True)),
                ('hashed_password', models.TextField(blank=True, null=True)),
                ('referredfrom', models.TextField(blank=True, null=True)),
                ('column_14', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '_user',
                'managed': False,
            },
        ),
    ]
