# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userfinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenseparticipants',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField(blank=True, null=True)),
                ('share', models.DecimalField(blank=True, decimal_places=15, max_digits=21, null=True)),
                ('object', models.TextField(blank=True, null=True)),
                ('acl', models.TextField(blank=True, null=True)),
                ('rperm', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('wperm', models.TextField(blank=True, null=True)),
                ('field_id', models.TextField(blank=True, db_column='_id', null=True)),
                ('settled', models.TextField(blank=True, null=True)),
                ('updated_at', models.TextField(blank=True, null=True)),
                ('participantname', models.TextField(blank=True, null=True)),
                ('participant', models.TextField(blank=True, null=True)),
                ('saved', models.IntegerField(blank=True, null=True)),
                ('column_14', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'expenseparticipants',
                'managed': False,
            },
        ),
    ]
