# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_expenseparticipants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expensedetails',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('field_id', models.TextField(blank=True, db_column='_id', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('wperm', models.TextField(blank=True, null=True)),
                ('acl', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('updated_at', models.TextField(blank=True, null=True)),
                ('object', models.TextField(blank=True, null=True)),
                ('addedby', models.TextField(blank=True, null=True)),
                ('shares', models.TextField(blank=True, null=True)),
                ('rperm', models.TextField(blank=True, null=True)),
                ('persons', models.TextField(blank=True, null=True)),
                ('distribution', models.TextField(blank=True, null=True)),
                ('owner', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('column_17', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'expensedetails',
                'managed': False,
            },
        ),
    ]
