# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_expensedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runningexpenses',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField(blank=True, null=True)),
                ('rperm', models.TextField(blank=True, null=True)),
                ('saved', models.IntegerField(blank=True, null=True)),
                ('agenda', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('contreemoney', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('updated_at', models.TextField(blank=True, null=True)),
                ('field_created_at', models.IntegerField(blank=True, db_column='_created_at', null=True)),
                ('acl', models.TextField(blank=True, null=True)),
                ('wperm', models.TextField(blank=True, null=True)),
                ('field_id', models.TextField(blank=True, db_column='_id', null=True)),
            ],
            options={
                'db_table': 'runningexpenses',
                'managed': False,
            },
        ),
    ]
