# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_runningexpenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updatelist',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_id', models.TextField(blank=True, db_column='_id', null=True)),
                ('wperm', models.TextField(blank=True, null=True)),
                ('id1', models.TextField(blank=True, null=True)),
                ('object', models.TextField(blank=True, null=True)),
                ('updated_at', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('dist', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('expenseid', models.TextField(blank=True, null=True)),
                ('new_val', models.TextField(blank=True, null=True)),
                ('rperm', models.TextField(blank=True, null=True)),
                ('acl', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('old_val', models.TextField(blank=True, null=True)),
                ('column_15', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'updatelist',
                'managed': False,
            },
        ),
    ]
