# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_updatelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fcm',
            fields=[
                ('instance_token', models.TextField(blank=True, null=True)),
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'FCM',
                'managed': False,
            },
        ),
    ]
