# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-13 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20161206_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('name', models.TextField(blank=True, null=True)),
                ('number', models.TextField(blank=True, null=True)),
                ('merchantNumber', models.TextField(blank=True, null=True)),
                ('privilege', models.TextField(blank=True, null=True)),
                ('fcmToken', models.TextField(blank=True, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Helper',
                'managed': False,
            },
        ),
    ]
